---
name: "GitHub Actions Example"

"on":
  pull_request:
  push: { branches: [main] }

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Check out code
        uses: actions/checkout@v2
        
        
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init
       
      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        
    deploy:
    needs: build
    name: Deploy to EKS
    runs-on: [self-hosted, prod]
    steps:
      - uses: actions/checkout@v3
      - name: Setup kubeconfig
 
        id: setup-kubeconfig
        run: |
          export AWS_PROFILE=${{ secrets.PROD_AWS_PROFILE }}
          aws eks --region eu-west-2 update-kubeconfig --name conigital-prod-eks-cluster
      - name: Update k8s manifest
        run: |
          cd k8s-manifests
          sed -i 's/aac2c87a39c449091b7d4d539b71362054002f22/${{ github.sha }}/g' prod_conop.yml
          kubectl apply -f prod_conop.yml
